name: "Post-Integration"

on:
  push:
    branches:
      - main
      - '!stable'
      - '!release'

jobs:
  merge-to-stable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_WORKFLOWS }}

      - name: Sets environment variables - branch-name
        uses: nelonoel/branch-name@v1.0.1

      - name: Sets environment variables - Nerdbank.GitVersioning
        uses: dotnet/nbgv@master
        with:
          setAllVars: true

      - name: Setup dotnet 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Setup dotnet 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Prepare build for unit tests
        run: |
          dotnet clean -c Debug
          dotnet restore
          dotnet build -c Debug /p:UseSourceLink=true --no-restore

      - name: Run unit tests
        run: dotnet test -c Debug --no-build

      - name: Merge to stable
        run: |
          git config --local user.email "atcnet.org@gmail.com"
          git config --local user.name "Atc-Net"
          git checkout stable
          git merge --ff-only main
          git push origin stable

      - name: Creating library package for pre-release
        run: dotnet pack -c Release --no-restore -o ${GITHUB_WORKSPACE}/packages -p:RepositoryBranch=$BRANCH_NAME -p:ContinuousIntegrationBuild=true -p:Version=${NBGV_NuGetPackageVersion}

      - name: Push packages to GitHub Package Registry
        run: |
          dotnet nuget push ${GITHUB_WORKSPACE}/packages/'Atc.Rest.ApiGenerator.'${NBGV_NuGetPackageVersion}'.nupkg' -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/atc-net/index.json --skip-duplicate
          dotnet nuget push ${GITHUB_WORKSPACE}/packages/'atc-api-gen.'${NBGV_NuGetPackageVersion}'.nupkg' -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/atc-net/index.json --skip-duplicate
